### ISSUE TITLE
Repackage as a proper CommonJS module to handle local jQuery object

### ISSUE THREAD

**Issue by rkpatel33** [j-ulrich/jquery-simulate-ext#36]
I was thinking about forking and refactoring this project to use CommonJS modules. I have a particular need where I need to extend a local instance of jQuery instead of overriding the global jQuery object. So something of the form:

```
module.exports = function ($) {
  ...
}
```

I was wondering if there was a reason you had not structured the project like this for publishing to npm. I am assuming it was mostly intended to use in the browser through HTML script tags? Figured I would check in as I started, thx.

**Comment by j-ulrich** [comment]
>  I am assuming it was mostly intended to use in the browser through HTML script tags?
Yes, exactly.
The project was inteded for distribution via Bower and then there was [a request](17) to make it available via npm. So I just did that without touching the project itself.

However, note that both jQuery Simulate Ext and its base project jQuery Simulate are not under active development and haven't been touched for quite some time.
So chances are high that there are severe issues with recent versions of browsers, npm, jQuery, etc.

**Comment by rkpatel33** [comment]
Thanks!  Anything else you suggest besides a full blown testing suite like selenium?

____________
Rishi K. Patel

On Mar 11, 2017, at 2:57 AM, Jochen Ulrich <notifications@github.com> wrote:

I am assuming it was mostly intended to use in the browser through HTML script tags?
Yes, exactly.
The project was inteded for distribution via Bower and then there was a request to make it available via npm. So I just did that without touching the project itself.

However, note that both jQuery Simulate Ext and its base project jQuery Simulate are not under active development and haven't been touched for quite some time.
So chances are high that there are severe issues with recent versions of browsers, npm, jQuery, etc.

**Comment by j-ulrich** [comment]
Not really, sorry. I'm not up to date with that topic anymore. :-/
