### ISSUE TITLE
click coordinate..

### ISSUE THREAD

**Issue by mt2009** [j-ulrich/jquery-simulate-ext#38]
why click coordinate is not working???

no difference between this two. it clicked the same spot (0,0)
$link.simulate("click", coord);
$link.simulate("click");

i tried all the coord combination, none of it work:
coord = { pageX: 100, pageY: 50 };
coord = { clientX: 100, clientY: 50 };
coord = { screenX: 100, screenY: 50 };

how to make it click custom coordinate?

**Comment by j-ulrich** [comment]
Simulating click events is implemented by [jquery-simulare](https://github.com/jquery/jquery-simulate) itself, not by jquery-simulare-ext.
So you would rather need to ask there.
But both projects are not under active development anymore. So I guess you should not expect much support there as well. :-( Sorry.
