### ISSUE TITLE
how can I simulate drag with a speed function?

### ISSUE THREAD

**Issue by imdoge** [j-ulrich/jquery-simulate-ext#40]
I don't want to drag with the same speed, can I config it?
thx

**Comment by j-ulrich** [comment]
I'm not sure what you mean with "drag with the same speed".

Using either the `duration` or the `stepDelay` property of the `interpolation` option allows to define how fast a drag is simulated (see [the documentation of drag](/j-ulrich/jquery-simulate-ext/blob/master/doc/drag-n-drop.md#drag))
For example:
```js
$(dragElement).simulate('drag-n-drop', {
	dropTarget: dropElement,
	interpolation: {
		stepWidth: 10,
		stepDelay: 50
	}
});
```
Increasing `stepDelay` makes the drag slower.

If you want to drag an element with different speeds (for example, slower at the beginning and then faster), then you need to simulate multiple successive drags:

```js
$(dragElement).simulate('drag', {
	dragTarget: firstPointOfDrag,
	interpolation: {
		stepWidth: 10,
		stepDelay: 50 // slower
	},
	callback: function() {
		$(dragElement).simulate('drag', {
			dragTarget: secondPointOfDrag,
			interpolation: {
				stepWidth: 10,
				stepDelay: 25 // faster
			},
			callback: function() {
				$(dragElement).simulate('drag-n-drop', {
					dropTarget: endPointOfDrag,
					interpolation: {
						stepWidth: 10,
						stepDelay: 75 // slower again
					}
				});
			}
		});
	}
});
```

Side note: Of course you can use promises (for example, [jQuery.Deferred()](http://api.jquery.com/category/deferred-object/)) to avoid nesting the callbacks.

Does that answer your question?

**Comment by imdoge** [comment]
thanks a lot
