### ISSUE TITLE
Key-Sequence with delay doesn't insert spaces into DIV or P tags in Chrome

### ISSUE THREAD

**Issue by mikegioia** [j-ulrich/jquery-simulate-ext#6]
I was successfully able to insert spaces into a textarea tag but the string "This is a test", when inserted into a DIV or P tag gave me "Thisisatest   " with the spaces at the end instead of between the words.

I ran this using jQuery 1.7.2, and on Chrome Version 26.0.1410.63 (Ubuntu).

**Comment by noelboss** [comment]
Doesn't work for me as well. Trying to simulate into a DIV... 
Safari Version 8.0.8 (10600.8.9)
jQuery v1.11.2
