### ISSUE TITLE
Make quirk detection optional

### ISSUE THREAD

**Issue by gjuggler** [j-ulrich/jquery-simulate-ext#9]
I'm using jquery-simulate-ext in a content-script environment where the DOM is fragile and behavior changes unexpectedly when DIVs are inserted or removed.

I tracked down one of our problems to the DOM manipulation that the key-sequence plugin uses to detect a quirk (i.e., https://github.com/j-ulrich/jquery-simulate-ext/blob/master/src/jquery.simulate.key-sequence.js#L430). I'm removing these lines from my own fork, but if there were a way to optionally disable the quirk detection I would find that useful.

**Comment by MishaAbesadze** [comment]
ctrl+v or control+v doesn't work :(

**Comment by j-ulrich** [comment]
See #30
